#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d   󰈹   󰊖        

bspc config border_width         1
bspc config window_gap          10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

xset s off -dpms
xrandr --output VGA-1 --mode 1440x900 -r 75
setxkbmap -layout us,ru -option grp:alt_shift_toggle
wmname LG3D
feh --bg-scale ~/Documents/wall8.jpg
~/.config/polybar/launch.sh
flameshot  

bspc config normal_border_color "#24283b"
bspc config focused_border_color "#7aa2f7"
